<<<<<<< HEAD
(part "IKD0103101"
    (packageRef "IKD0103101")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "Apem")
    (property "Manufacturer_Part_Number" "IKD0103101")
    (property "Mouser_Part_Number" "642-IKD0103101")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Apem/IKD0103101/?qs=4WAgjVhLeNDRnoT6kDTfJA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "1 Way Surface Mount DIP Switch SPST, Raised Actuator Slide Actuator")
    (property "Datasheet_Link" "https://eu.mouser.com/datasheet/2/26/appm_s_a0001640570_1-2262042.pdf")
    (property "symbolName1" "IKD0103101")
)
=======
(part "IKD0103101"
    (packageRef "IKD0103101")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "Apem")
    (property "Manufacturer_Part_Number" "IKD0103101")
    (property "Mouser_Part_Number" "642-IKD0103101")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Apem/IKD0103101/?qs=4WAgjVhLeNDRnoT6kDTfJA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "1 Way Surface Mount DIP Switch SPST, Raised Actuator Slide Actuator")
    (property "Datasheet_Link" "https://eu.mouser.com/datasheet/2/26/appm_s_a0001640570_1-2262042.pdf")
    (property "symbolName1" "IKD0103101")
)
>>>>>>> ec84c6f (Update Firmware MQ135.)
